---
# tasks file for osd-filestore-setup

- name: Calling ceph-volume on the OSD devices
  shell:
     cmd: ceph-volume lvm create --filestore --data {{ item.data }} --journal {{ item.journal }}
  with_items: "{{ osd_devices }}"
  ignore_errors: yes
