
- name: Perform specific tasks on hosts
  hosts: all
  become: yes
  roles:
  - common
  tags:
  - node_setup
  - configure_bluestore_nodes

- name: Bootstrapping the ceph monitors
  become: yes
  hosts: ceph_mons
  roles:
  - monitor-bootstrap
  vars:
     ceph_deployment_node: ceph-1

- name: Configuring OSD nodes for bluestore backend
  become: yes
  hosts: ceph_osds_bluestore
  roles:
  - osd-setup
  vars:
     osd_devices:
     - /dev/vdb
     - /dev/vdc
     - /dev/vdd
     - /dev/vde
     partition_layout:
     - { num: 1, start: "0%", end: "100%" }
     ceph_deployment_node: ceph-1
  tags:
  - configure_bluestore_nodes

- name: Setting up OSD nodes with bluestore backend
  become: yes
  hosts: ceph_osds_bluestore
  roles:
  - osd-bluestore-setup
  vars:
     osd_devices:
     - { data: "/dev/vdb1" }
     - { data: "/dev/vdc1" }
     - { data: "/dev/vdd1" }
     - { data: "/dev/vde1" }
     ceph_deployment_node: ceph-1

- name: Configuring OSD nodes for filestore backend
  become: yes
  hosts: ceph_osds_filestore
  roles:
  - osd-setup
  vars:
     osd_devices:
     - /dev/vdb
     - /dev/vdc
     - /dev/vdd
     - /dev/vde
     partition_layout:
     - { num: 1, start: "0%", end: "2%" }
     - { num: 2, start: "2%", end: "100%" }
     ceph_deployment_node: ceph-1
  tags:
  - configure_filestore_nodes

- name: Configuring OSD nodes
  become: yes
  hosts: ceph_osds_filestore
  roles:
  - osd-filestore-setup
  vars:
     osd_devices:
     - { data: "/dev/vdb2", journal: "/dev/vdb1" }
     - { data: "/dev/vdc2", journal: "/dev/vdc1" }
     - { data: "/dev/vdd2", journal: "/dev/vdd1" }
     - { data: "/dev/vde2", journal: "/dev/vde1" }
     ceph_deployment_node: ceph-1
