---
# tasks file for common

- name: Update host
  apt:
     upgrade: dist
     update_cache: yes
  notify:
  - reboot nodes

- name: Installing required packages
  apt:
     pkg:
     - ceph-common
     - ceph
     - sshpass
     state: latest
     update_cache: yes
